import type { Metadata } from "next";
import { geistSans } from "@/config/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: {
    template: "%s - Jacaranda Shop",
    default: "Home - Jacaranda Shop"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistSans.variable} antialiased`}
      >
      
      {children}
      
      </body>
    </html>
  );
}
